# Generated by Django 4.2.3 on 2023-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicdesks', '0003_alter_ann_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreply',
            name='status',
        ),
        migrations.AddField(
            model_name='userreply',
            name='approved_userreply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
